# Server Port Mapping Configuration
server.port=8080

# Spring Application Metadata
spring.application.name=food-delivery-backend

# Spring Data Source Core Database Connectivity Setup
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



# Enable descriptive SQL logging in the console for transparent query auditing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Platform Dialect Translation Blueprint
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
