spring.application.name=fooddelivery05
spring.profiles.active=local

# Razorpay Key id and Key secret for Payment Integration

razorpay.key.id= rzp_test_Tjs1HqvCra5ULD
razorpay.key.secret= P0xmEdVrXFAPb56fLiBjeiSi